In [8]:
import numpy as np
import pandas as pd

## 1 Cargar dataSet

In [3]:
df = pd.read_csv("IT Salary Survey EU 2019.csv")

In [4]:
df

Zeitstempel   Age Gender       City Seniority level  \
0    02.12.2019 11:18:26  33.0   Male     Berlin          Senior   
1    02.12.2019 11:18:35  29.0   Male     Berlin          Middle   
2    02.12.2019 11:18:56   NaN   Male     Berlin          Middle   
3    02.12.2019 11:19:08  30.0   Male     Berlin          Senior   
4    02.12.2019 11:19:37  32.0   Male     Berlin          Senior   
..                   ...   ...    ...        ...             ...   
986  07.01.2020 09:23:01  30.0   Male  Amsterdam          Senior   
987  07.01.2020 10:08:18  28.0   Male  Amsterdam          Senior   
988  07.01.2020 16:52:43  42.0   Male     Munich          Senior   
989  08.01.2020 11:18:41  33.0   Male     Berlin          Senior   
990  08.01.2020 22:20:08  32.0   Male  Frankfurt          Middle   

    Position (without seniority)  Years of experience  \
0            Fullstack Developer                   13   
1              Backend Developer                    3   
2               Mobile Developer                    4   
3              Backend Developer                    6   
4             Embedded Developer                   10   
..                           ...                  ...   
986            Backend Developer                   10   
987            Security Engineer                    7   
988                      Manager                    9   
989           Software Architect                   15   
990          Fullstack Developer                    5   

    Your main technology / programming language  \
0                                           PHP   
1                                        Python   
2                                        Kotlin   
3                                           PHP   
4                                         C/C++   
..                                          ...   
986                                      Python   
987                                Not Relevant   
988                                Not Relevant   
989                     Javascript / Typescript   
990                                        Java   

     Yearly brutto salary (without bonus and stocks)  Yearly bonus  ...  \
0                                            64000.0        1000.0  ...   
1                                            55000.0           NaN  ...   
2                                            70000.0           NaN  ...   
3                                            63000.0           NaN  ...   
4                                            66000.0           NaN  ...   
..                                               ...           ...  ...   
986                                          71000.0        3000.0  ...   
987                                          72000.0           0.0  ...   
988                                          68000.0       10000.0  ...   
989                                         100000.0        3000.0  ...   
990                                          63000.0           NaN  ...   

     Yearly stocks one year ago. Only answer if staying in same country  \
0                                                  NaN                    
1                                                  NaN                    
2                                                  NaN                    
3                                                  NaN                    
4                                                  NaN                    
..                                                 ...                    
986                                                0.0                    
987                                                0.0                    
988                                                NaN                    
989                                                NaN                    
990                                                NaN                    

     Number of vacation days  Number of home office days per month  \
0                       29

## 2 Números aleatorios

In [12]:
from numpy.random import randint

In [195]:
def numerosUnicos(n):
    np.random.seed(123)
    lista = [randint(0,n*50,1)]
    i= 1
    unico = False
    while (i<n):
        while(unico== False):
            x= randint(0,n*50,1)
            unico = True
            for j in lista:
                if x== j:
                    unico = False
                    break
        lista.append(x)
        i+= 1
        unico = False
    return lista
                    
                    
    

In [196]:
ls_prueba= numerosUnicos(30)
ls_prueba

[array([1389]),
 array([1406]),
 array([1346]),
 array([1122]),
 array([1041]),
 array([106]),
 array([1147]),
 array([1238]),
 array([96]),
 array([113]),
 array([638]),
 array([47]),
 array([73]),
 array([942]),
 array([224]),
 array([111]),
 array([1433]),
 array([1363]),
 array([846]),
 array([1277]),
 array([420]),
 array([608]),
 array([1232]),
 array([1092]),
 array([451]),
 array([2]),
 array([340]),
 array([39]),
 array([596]),
 array([504])]

## 3 Numero de registros y columnas

In [21]:
len(df.columns)

23

In [27]:
len(df.index)


991

In [29]:
print(f'El dataFrame tiene {len(df.index)} registros y {len(df.columns)} columnas')


El dataFrame tiene 991 registros y 23 columnas


## 4 Valores ausentes por columna

In [31]:
df.isna().sum()

Zeitstempel                                                                                               0
Age                                                                                                     109
Gender                                                                                                    0
City                                                                                                      0
Seniority level                                                                                          15
Position (without seniority)                                                                              1
Years of experience                                                                                       0
Your main technology / programming language                                                              14
Yearly brutto salary (without bonus and stocks)                                                           1
Yearly bonus                

In [30]:
df.isnull().sum()

Zeitstempel                                                                                               0
Age                                                                                                     109
Gender                                                                                                    0
City                                                                                                      0
Seniority level                                                                                          15
Position (without seniority)                                                                              1
Years of experience                                                                                       0
Your main technology / programming language                                                              14
Yearly brutto salary (without bonus and stocks)                                                           1
Yearly bonus                

## 5 Proporción de valores ausentes por columna

In [33]:
df.isnull().mean()

Zeitstempel                                                                                             0.000000
Age                                                                                                     0.109990
Gender                                                                                                  0.000000
City                                                                                                    0.000000
Seniority level                                                                                         0.015136
Position (without seniority)                                                                            0.001009
Years of experience                                                                                     0.000000
Your main technology / programming language                                                             0.014127
Yearly brutto salary (without bonus and stocks)                                                 

## 6 Numero de valores ausentes en la tabla

In [38]:
df_nulo=df.isnull().sum()

In [41]:
type(df_nulo)

pandas.core.series.Series

In [42]:
df_nulo.sum()

5724

## 7 Muestre el salario promedio por genero

In [46]:
df[["Gender","Yearly brutto salary (without bonus and stocks)"]].groupby("Gender").mean()

Yearly brutto salary (without bonus and stocks)
Gender                                                 
Female                                     62725.751634
Male                                       74360.274791

## 8 Número de empleados por genero

In [63]:
df_sex=df[["Gender","Zeitstempel"]].groupby("Gender").count()

In [64]:
df_sex

Zeitstempel
Gender             
Female          153
Male            838

## 9 Sueldo promedio por nivel de señority

In [71]:
df[["Seniority level","Yearly brutto salary (without bonus and stocks)"]].groupby("Seniority level").mean()

Yearly brutto salary (without bonus and stocks)
Seniority level                                                 
Head                                                92333.333333
Junior                                              46834.722222
Lead                                                94187.057143
Middle                                              61590.209559
Principal                                          115000.000000
Senior                                              78971.390119

## 10 Variable años experiencia- sueldo

In [74]:
df_sueldoY = df[["Years of experience","Yearly brutto salary (without bonus and stocks)"]].groupby("Years of experience").mean()

In [75]:
df_sueldoY

Yearly brutto salary (without bonus and stocks)
Years of experience                                                 
0                                                       50416.666667
1                                                       45550.000000
2                                                       53404.945455
3                                                       54991.579710
4                                                       62194.642857
5                                                       69027.692308
6                                                       70522.211268
7                                                       72397.974684
8                                                       77528.267442
9                                                       81775.000000
10                                                      80611.111111
11                                                      82600.000000
12                                                      88350.377358
13                                                      75363.333333
14                                                      80211.714286
15                                                      76325.000000
16                                                      78821.739130
17                                                      80944.444444
18                                                      83746.153846
19                                                      68742.857143
20                                                      91571.428571
22                                                     100750.000000
24                                                     115000.000000
25                                                      86266.666667
28                                                     110000.000000
30                                                      60000.000000

## 11 Generar tablas 

In [88]:
df_tec = df[["Your main technology / programming language","Yearly brutto salary (without bonus and stocks)"]].groupby("Your main technology / programming language").mean()

In [102]:
df_sort_tec=df_tec.sort_values(by=['Yearly brutto salary (without bonus and stocks)'], ascending=False)
df_sort_tec

Yearly brutto salary (without bonus and stocks)
Your main technology / programming language                                                 
Solidity                                                                       140000.000000
Google Cloud                                                                   101800.000000
Rust                                                                            92666.666667
K8S                                                                             85000.000000
Go                                                                              82293.333333
Perl                                                                            82000.000000
Kubernetes                                                                      80600.000000
Clojure                                                                         80000.000000
Not Relevant                                                                    77337.815126
Scala                                                                           77333.333333
SAP / ABAP                                                                      77200.000000
C/C++                                                                           75861.363636
Python                                                                          74621.568627
ASM                                                                             74000.000000
AWS                                                                             73793.333333
Java                                                                            73744.132597
Swift                                                                           72400.000000
Yaml                                                                            72000.000000
Multiple                                                                        70000.000000
Openstack                                                                       70000.000000
Objective-C                                                                     70000.000000
R                                                                               69876.923077
.NET                                                                            68599.390244
ABAP                                                                            68000.000000
Javascript / Typescript                                                         67737.009346
PHP                                                                             67332.250000
Azure                                                                           67114.285714
Cobol                                                                           67000.000000
SQL                                                                             65692.307692
Kotlin                                                                          65643.676471
Unity                                                                           65000.000000
HR                                                                              65000.000000
Ruby                                                                            63770.000000
Cisco                                                                           63500.000000
Elixir                                                                          57073.000000
Linux-Stack, Networking                                                         56300.000000
Powershell                                                                      55000.000000
SAS                                                                             47650.000000
Microsoft, Vmware                                                               45000.000000
Erlang                                                                          36819.000000
Hadoop                                                                          32000.000000
PostgreSQL                                    

In [99]:
df_tres= df_sort_tec.iloc[0:3, :]

In [100]:
df_tres

Yearly brutto salary (without bonus and stocks)
Your main technology / programming language                                                 
Solidity                                                                       140000.000000
Google Cloud                                                                   101800.000000
Rust                                                                            92666.666667

In [105]:
df_tres.index.values

array(['Solidity', 'Google Cloud', 'Rust'], dtype=object)

In [126]:
ls_tec=[]
for i in df_tres.index.values:
    ls_tec.append(i)

In [166]:
ls_tec

['Solidity', 'Google Cloud', 'Rust']

No se porque no funciona lo siguiente y ya no se me ocurre entonces lo haré a mano, pero agradecería la retroalimentación

In [193]:
df_nuevo= pd.DataFrame()
df_aux= pd.DataFrame()
for i in range(3):
    aux=df.loc[(df["Your main technology / programming language"]== ls_tec[i]), ["Gender","Age","Seniority level","Years of experience","Your main technology / programming language","Yearly brutto salary (without bonus and stocks)"]]
    df_aux=df_nuevo.append(aux)
    df_nuevo= df_aux

    

Entonces aplicamos el plan B, ya jala pero lo dejamos como anecdota (Además no entendí del todo porque funciono) y dos soluciones xd

In [174]:
df_nuevo=df.loc[(df["Your main technology / programming language"]== ls_tec[0]) | (df["Your main technology / programming language"]== ls_tec[1]) |(df["Your main technology / programming language"]== ls_tec[2]), :]

In [178]:
df_nuevo

Gender   Age Seniority level  Years of experience  \
648   Male  41.0          Senior                   20   
125   Male  35.0       Principal                   15   
129   Male  32.0          Senior                   14   
193   Male  47.0          Middle                   22   
274   Male  33.0          Senior                   10   
792   Male  30.0          Senior                   15   
645   Male  34.0          Senior                   14   
655   Male  25.0          Senior                    8   
943   Male  27.0          Senior                    8   

    Your main technology / programming language  \
648                                    Solidity   
125                                Google Cloud   
129                                Google Cloud   
193                                Google Cloud   
274                                Google Cloud   
792                                Google Cloud   
645                                        Rust   
655                                        Rust   
943                                        Rust   

     Yearly brutto salary (without bonus and stocks)  
648                                         140000.0  
125                                         120000.0  
129                                          92000.0  
193                                         100000.0  
274                                          80000.0  
792                                         117000.0  
645                                          86000.0  
655                                         110000.0  
943                                          82000.0

In [197]:
df_nuevo=df_nuevo.assign(numbers= numerosUnicos(9))

In [198]:
df_nuevo

Gender   Age Seniority level  Years of experience  \
648   Male  41.0          Senior                   20   
125   Male  35.0       Principal                   15   
129   Male  32.0          Senior                   14   
193   Male  47.0          Middle                   22   
274   Male  33.0          Senior                   10   
792   Male  30.0          Senior                   15   
645   Male  34.0          Senior                   14   
655   Male  25.0          Senior                    8   
943   Male  27.0          Senior                    8   

    Your main technology / programming language  \
648                                    Solidity   
125                                Google Cloud   
129                                Google Cloud   
193                                Google Cloud   
274                                Google Cloud   
792                                Google Cloud   
645                                        Rust   
655                                        Rust   
943                                        Rust   

     Yearly brutto salary (without bonus and stocks) numbers  
648                                         140000.0   [365]  
125                                         120000.0   [382]  
129                                          92000.0   [322]  
193                                         100000.0    [98]  
274                                          80000.0   [230]  
792                                         117000.0    [17]  
645                                          86000.0    [83]  
655                                         110000.0   [106]  
943                                          82000.0   [123]

In [199]:
df_nuevo.to_csv("tres_tecnologias.csv", index=False)

In [ ]:
import 

In [201]:
df_nuevo.to_excel("tres_tecnologias.xlsx", index=False)